## Ink — material factory + shared palette.
##
## Every toon material in the scene is a duplicate of materials/toon_base.tres with
## a different base_color, so tweaking band count / shadow tint / ink weight in that
## one .tres restyles the whole scene. Duplicates are cached per colour so the group
## of characters doesn't compile a shader variant each.
class_name Ink
extends RefCounted

const TOON_BASE := "res://materials/toon_base.tres"
## Ink weight at outline = 1.0. Angular, not world-space — see outline.gdshader.
const OUTLINE_BASE := 0.0045

static var _cache: Dictionary = {}

## A toon material tinted [param color].
## [param outline] multiplies the ink weight — 0.0 drops the outline entirely
## (use that for the ground plane, whose inverted hull would be a giant box).
static func mat(color: Color, outline: float = 1.0, bands: int = 3) -> ShaderMaterial:
	var key := "%s|%.3f|%d" % [color.to_html(), outline, bands]
	if _cache.has(key):
		return _cache[key]

	var base: ShaderMaterial = load(TOON_BASE)
	var m: ShaderMaterial = base.duplicate(true)
	m.set_shader_parameter("base_color", color)
	m.set_shader_parameter("band_count", bands)

	if outline <= 0.0:
		m.next_pass = null
	else:
		var op := m.next_pass as ShaderMaterial
		if op:
			op.set_shader_parameter("thickness", OUTLINE_BASE * outline)

	_cache[key] = m
	return m


# --- Faces -------------------------------------------------------------------

## How many face cards live in res://faces/. Generated by art/facegen.py from
## four pen drawings: the first four are the drawings untouched, the rest are
## those same four mirrored, squeezed, re-browed and re-penned.
const FACE_COUNT := 20

static var _faces: Dictionary = {}

## The head is a drawing on paper, so its material is unlit: ink stays ink under
## every light in the scene, which is what a printed page does.
static func face_mat(index: int) -> StandardMaterial3D:
	var i := posmod(index, FACE_COUNT)
	if _faces.has(i):
		return _faces[i]

	var m := StandardMaterial3D.new()
	m.albedo_texture = load("res://faces/face_%02d.png" % i)
	m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	# A depth pre-pass, not plain alpha blending: twenty heads overlap in the
	# crowd at the rock, and blended surfaces sort per-object, so without this
	# a face in the back row draws over one in the front.
	m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA_DEPTH_PRE_PASS
	m.alpha_scissor_threshold = 0.5
	# Drawn from both sides, so the card cannot be facing the wrong way.
	m.cull_mode = BaseMaterial3D.CULL_DISABLED
	m.texture_filter = BaseMaterial3D.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS
	_faces[i] = m
	return m


## The back of a head: inferred from the front by art/bodygen.py.
static func back_mat(index: int) -> StandardMaterial3D:
	return _paper("res://faces/back_%02d.png" % posmod(index, FACE_COUNT))


## A costume part, drawn in pen by art/bodygen.py. [param part] is one of
## torso_f, torso_b, arm, leg; [param role_key] is Arch.ROLE_KEY[role].
static func body_mat(role_key: String, part: String) -> StandardMaterial3D:
	return _paper("res://bodies/%s_%s.png" % [role_key, part])


static var _paper_cache: Dictionary = {}

## Unlit, scissored, two-sided: a drawing on paper, same as the faces.
static func _paper(path: String) -> StandardMaterial3D:
	if _paper_cache.has(path):
		return _paper_cache[path]
	var m := StandardMaterial3D.new()
	m.albedo_texture = load(path)
	m.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	m.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA_DEPTH_PRE_PASS
	m.alpha_scissor_threshold = 0.5
	m.cull_mode = BaseMaterial3D.CULL_DISABLED
	m.texture_filter = BaseMaterial3D.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS
	_paper_cache[path] = m
	return m


# --- Scene palette -----------------------------------------------------------
# Warm paper, cool shadows, desaturated fills. Nothing fully saturated: printed
# colour never is, and it's what keeps the ink lines reading as the darkest thing
# on screen.

const PAPER := Color("efe7d6")
const INK := Color("12101a")

const GRASS := Color("7d9560")
const GRASS_DARK := Color("62784b")
const DIRT := Color("b9a07c")
const BARK := Color("8a6f55")
const LEAF_A := Color("7fa35f")
const LEAF_B := Color("93b46d")
const LEAF_C := Color("6d8f52")
const STONE := Color("b3ada2")

const SKINS: Array[Color] = [
	Color("e8c4a0"), Color("d4a276"), Color("a9714b"),
	Color("8d5524"), Color("f2d5b8"), Color("6b4429"),
]
const SHIRTS: Array[Color] = [
	Color("c4614f"), Color("5b7fa6"), Color("d8a94b"),
	Color("7a9b6e"), Color("9a6a99"), Color("c9c0aa"), Color("4f6b72"),
]
const PANTS: Array[Color] = [
	Color("4a5468"), Color("6b5a4a"), Color("3f4a52"),
	Color("87796a"), Color("5a4e63"),
]
const HAIRS: Array[Color] = [
	Color("2b2320"), Color("4a3226"), Color("7a5637"),
	Color("b08347"), Color("8f8f8f"), Color("a8442f"),
]

const NAMES: Array[String] = [
	"Wren", "Bosch", "Marguerite", "Tully", "Okonkwo", "Pip",
	"Halvard", "Nim", "Aster", "Crane", "Bramble", "Rook",
	"Sable", "Fen", "Quill", "Oleander", "Juniper", "Moss",
	"Ingrid", "Tamsin", "Obi", "Linden", "Hazel", "Corvin",
	"Petra", "Rafe", "Ottoline", "Sorrel", "Birch", "Lark",
]
